spring.application.name=backend
server.port=${SERVER_PORT:9090}
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petclinic_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
management.endpoints.web.exposure.include=health
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

security.jwt.secret=${JWT_SECRET:9f2c8a7e6d1b4c3f8a9d2e7c1b6a4d9e8f3c2b7a1d6e9f0c8b5a2d7e4f1c9b8}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}